# Generated by Django 2.2.2 on 2019-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='headimage',
            field=models.ImageField(upload_to='headimage'),
        ),
        migrations.AlterField(
            model_name='mypicture',
            name='pic',
            field=models.ImageField(upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='headimage',
            field=models.ImageField(upload_to='headimage'),
        ),
    ]
